highlighter: rouge
permalink: pretty
title: "Adam Robinson Lighting"
description: "Website for Adam Robinson Lighting"
color: "#D1880A"
keywords: "adam robinson lighting and sound"
twitter: "@lukejpreston"
navigation: [ { name: "home", href: ""}]
footer: {
    left: "Adam Robinson Lighting",
    right: "Home for lighting and sound",
    icons: [{href: "https://github.com/lukejpreston/adroblighting", kind: "github"}]
  }
url: "http://lukejpreston.github.io/adroblighting"
email: "lukejpreston@gmail.com"
owner: "Adam Robinson"
